version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks: 
      localnetwork:  
  my-wp:
    image: wordpress
    hostname: shop.local
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: 12345678
    networks: 
      localnetwork:  
        aliases: 
          - shop.local
networks:
  localnetwork: